version: "3.8"

services:
  bisection:
    build: ./methods/bisection
    container_name: bisection
    ports:
      - "5001:5001"

  fixed-point:
    build: ./methods/fixed-point
    container_name: fixed-point
    ports:
      - "5002:5002"

  newton-raphson:
    build: ./methods/newton-raphson
    container_name: newton-raphson
    ports:
      - "5003:5003"

  secant:
    build: ./methods/secant
    container_name: secant
    ports:
      - "5004:5004"

  jacobi:
    build: ./methods/jacobi
    container_name: jacobi
    ports:
      - "5006:5006"

  gauss-seidel:
    build: ./methods/gauss-seidel
    container_name: gauss-seidel
    ports:
      - "5007:5007"

  runner:
    build: ./runner
    container_name: runner
    ports:
      - "5000:5000"
    depends_on:
      - bisection
      - fixed-point
      - newton-raphson
      - secant
      - jacobi
      - gauss-seidel
